### PR TITLE
fix mailing label, new comments, and subscribe and save manage your deliveries links

### LINKED ISSUE #23: Print return label from email link does not work
Return package email contains print label link:
https://www.amazon.com/gp/f.html?C=blah&K=blah&R=blah&T=C&U=https%3A%2F%2Fwww.amazon.com%2Freturns%2Flabel%2F9ceeablah-blah%2FrmaID%2FDckf6ZftRRMA%3Fref_%3Dpe_1811570_blah_E_Label_Page&A=blah&H=blah&ref_=pe_1811570_136791410_E_Label_Page

Result is smile homepage instead of printing label page.

### PR DESCRIPTION
**Pull request by bbodenmiller**
fix #23

### CODE REVIEW

**Comment by kd7lxl** [comment]
Just tested, this also fixes links in "New comment on..." notification emails, such as the "See this post" and "Reply to this post" links.

If you're interested in tests for these, I can submit a PR to bbodenmiller:return-labels.

**Comment by bbodenmiller** [comment]
I'd welcome those tests in my branch. Hopefully we can get the author to update play store soon too.

**Comment by bbodenmiller** [comment]
@Jdhaimson any chance of merging and publishing an update? This fixes many issues with emails that have existed for sometime.

**Comment by Jdhaimson** [comment]
Absolutely, thanks for working on this and sorry I just noticed these pull
requests. I'll be away from my laptop for the next week but I'll push out
the update once I'm back.

**Pull request merged**
