### PR TITLE
also support amazon.de (fixes #31)

### LINKED ISSUE #31: Feature request: Amazon Smile for Germany
Hi, and thanks for a great extension!

Amazon [just launched](https://www.heise.de/newsticker/meldung/Amazon-Smile-Kaufen-und-spenden-lassen-3463913.html) the Smile program in Germany. 

* Would you be open to include that in your extension? Or do you want to keep a US focus?
* How would this be implemented from a technical point? Would we add a permission for accessing "data on amazon.de" and rewrite those? I presume the same regexps (apart from the TLD) would still apply.
* Would you be willing to turn this extension into a multilingual project? 

Once we've discussed those, I'd happy look at contributing a PR. I've not done a Chrome extension, but feel somewhat confident I could still handle it. I'm not sure if I could be bothered with the translations, albeit it would be useful for a German Chrome Web store (not sure if there's different stores?)

### PR DESCRIPTION
**Pull request by schwabe**

### CODE REVIEW

**Comment by schwabe** [comment]
Oops I noticed that there is already another pull request. Just pick the one you like and I don't mind if close this one.

**Comment by schwabe** [comment]
I pushed a version of this to the chrome store since my fellow fablab members wanted to use it: https://chrome.google.com/webstore/detail/smile-always-internationa/oapkdpnnbeojdllbfldeoaelnadjhnkn

**Comment by delitzer** [comment]
Merged other PR. Uploading new version to Chrome store for approval now.

**Comment by delitzer** [comment]
Hey Arne, thanks for taking the initiative on this. We've update the main
version of SmileAlways to include support for both Amazon.de and
Amazon.co.uk. Would you please take down the version you uploaded to the
Chrome store to avoid confusion?

**Comment by schwabe** [comment]
Sure

**Pull request closed without merging**
